services:
  - type: web
    name: aeu-yazilim
    env: python
    region: frankfurt
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --config gunicorn_config.py"
    plan: free
    autoDeploy: true
